name: Unity CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build WebGL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Build WebGL
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          buildName: swordofshadows
          buildsPath: build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebGL-Build
          path: build/WebGL
  dockerize:
    name: Create Docker Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download WebGL Build artifact
        uses: actions/download-artifact@v4
        with:
          name: WebGL-Build
          path: build/WebGL

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/swordofshadows:latest .
  performance-test:
    name: Performance Testing with Artillery
    runs-on: ubuntu-latest
    needs: dockerize
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      
      - name: Start container in background
        run: |
          docker run -d --name perf-test -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/swordofshadows:latest
          sleep 10
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install Artillery
        run: npm install -g artillery
          
      - name: Run performance test
        run: |
          artillery run --config artillery.config.yml
          artillery quick --count 10 -n 5 http://localhost:8080 || echo "Smoke test completed"
          
      - name: Cleanup
        run: |
          docker stop perf-test
          docker rm perf-test

  push:
    name: Push Docker Image
    runs-on: ubuntu-latest
    needs: performance-test
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/swordofshadows:latest
